version: "3.3"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"  # Consider removing this and setting a password
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
  web:
    depends_on:
      - postgres
      - redis
    image: hub-private.parspooyesh.net/glitchtip-parspooyesh:latest
    ports:
      - 8111:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes: 
      - uploads:/code/uploads
      - ./sources.list.d/debian.sources:/etc/apt/sources.list.d/debian.sources
  worker:
    depends_on:
      - postgres
      - redis
    image: hub-private.parspooyesh.net/glitchtip-parspooyesh:latest
    command: ./bin/run-celery-with-beat.sh
    env_file:
      - .env
    restart: unless-stopped
    volumes: 
      - uploads:/code/uploads
  migrate:
    depends_on:
      - postgres
      - redis
    image: glitchtip/glitchtip
    command: "./manage.py migrate"
    env_file:
      - .env

volumes:
  pg-data:
  uploads:
